name: License check

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          config-file: ospo-sandbox/ospo-test/.github/dependency-review-config.yml@main
          vulnerability-check: false
          license-check: true
